language: objective-c
osx_image: xcode8
install:
  - carthage bootstrap --no-use-binaries
matrix:
  include:

    # iOS 9.3
    - script:
      - >-
        xcodebuild
        build-for-testing test-without-building
        -project Iris.xcodeproj
        -scheme Iris-iOS
        -sdk iphonesimulator
        -destination "platform=iOS Simulator,name=iPhone 6s,OS=9.3"
        -configuration Release

    # iOS 10.0
    - script:
      - >-
        xcodebuild
        build-for-testing test-without-building
        -project Iris.xcodeproj
        -scheme Iris-iOS
        -sdk iphonesimulator
        -destination "platform=iOS Simulator,name=iPhone 7,OS=10.0"
        -configuration Release

    # tvOS 9.2
    - script:
      - >-
        xcodebuild
        build-for-testing test-without-building
        -project Iris.xcodeproj
        -scheme Iris-tvOS
        -sdk appletvsimulator
        -destination "platform=tvOS Simulator,name=Apple TV 1080p,OS=9.2"
        -configuration Release

    # tvOS 10.0
    - script:
      - >-
        xcodebuild
        build-for-testing test-without-building
        -project Iris.xcodeproj
        -scheme Iris-tvOS
        -sdk appletvsimulator
        -destination "platform=tvOS Simulator,name=Apple TV 1080p,OS=10.0"
        -configuration Release

    # macOS
    - script:
      - >-
        xcodebuild
        build test
        -project Iris.xcodeproj
        -scheme Iris-macOS
        -sdk macosx
        -destination "arch=x86_64"
        -configuration Release
